apiVersion: v1
kind: ConfigMap
metadata:
  name: opspulse-config
  namespace: opspulse
data:
  PORT: "5000"
  MONGODB_URI: "mongodb://mongodb-service:27017/opspulse"
  CLIENT_URL: "http://localhost:30080"
  NODE_ENV: "production"
